# Generated by Django 3.2 on 2021-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuansu_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
